
// THIS CODE WAS GENERATED BY A TOOL.
// PLEASE DO NOT ALTER IT.
// ALL CLASSES ARE DECLARED PARTIAL SO YOU CAN MODIFY BEHAVIOUR EXTERNALLY

using BicepRunner;




public class SingleParamWeathertypeOptions : BicepOptions {
    private  SingleParamWeathertypeOptions(string bicepValue): base(bicepValue) {
    }
    public static readonly SingleParamWeathertypeOptions rain = new ("rain");
    public static readonly SingleParamWeathertypeOptions hail = new ("hail");
}

public partial class SingleParamModule : BicepResourceGroupScopeTemplate<SingleParamModule.SingleParamOutput> {
    public override string FileName => "single-param.bicep";
    public override string FileHash => "wiYzY1I4ws2TGeLFA8/M1KcNb+iGxRtLpfdWV9O+PAZXkyjrHsB6Ay4Ywe3V++cwsk7c71/PnK+qNM0QepjBTQ==";


    private string _name = default!;
    public string Name { get => this._name; set { this._name = value; } }


    private BicepTestTypes.SampleComplexObject _complex = default!;
    public BicepTestTypes.SampleComplexObject Complex { get => this._complex; set { this._complex = value; } }


    private BicepTestTypes.SampleComplexObject[] _names = default!;
    public BicepTestTypes.SampleComplexObject[] Names { get => this._names; set { this._names = value; } }


    private System.Array _names2 = default!;
    public System.Array Names2 { get => this._names2; set { this._names2 = value; } }


    private SingleParamWeathertypeOptions _weatherType = default!;
    public SingleParamWeathertypeOptions Weathertype { get => this._weatherType; set { this._weatherType = value; } }


    public partial class SingleParamOutput : BicepOutput {
        

        private string _nameout = default!;
        public string Nameout { get => this._nameout; set { this._nameout = value; } }


        private BicepTestTypes.SampleComplexObjectOutput _strongtype = default!;
        public BicepTestTypes.SampleComplexObjectOutput Strongtype { get => this._strongtype; set { this._strongtype = value; } }

        public SingleParamOutput(Dictionary<string, object> outputs) {
            base.SetProperties(outputs);
        }
    }

    public override Dictionary<string, object> BuildParameters() {
        var dictionary = new Dictionary<string, object>();
        dictionary["weatherType"] = new { value = this._weatherType.BicepValue};
        dictionary["name"] = new { value = this._name};
        dictionary["complex"] = new { value = this._complex};
        dictionary["names"] = new { value = this._names};
        dictionary["names2"] = new { value = this._names2};
        return dictionary;
    } 

    public override SingleParamOutput BuildOutput(Dictionary<string, object> outputs) {
        return new SingleParamOutput(outputs);
    } 
}
